import test from 'node:test';
import assert from 'node:assert/strict';
import {crystalSystem,csvToRequests,parseCSV,inputTemplate,predictionCSV,encodeCSV,validatePredictions,profileGeometry,friendlyError} from '../frontend/assets/ui_utils.mjs';

function prediction(low=0,high=1,voltage=3.4650564309719782){return {run_id:'test_run',working_ion:'Li',predicted_voltage_V:voltage,interval:{formula_charge:'FePO4',formula_discharge:'LiFePO4',ion_per_host_charge:low,ion_per_host_discharge:high,fracA_charge:0,fracA_discharge:1/7},model:{family:'dnn',training_population:'li_only',candidate_id:'dnn_scaled_0'},evaluation_reference:{scope:'li_only_grouped_holdout',all:{mae_V:.7}},extrapolates_working_ion:false,changed_training_constant_features:0,warnings:['Test fixture only']};}

test('crystal-system boundaries match the backend rules',()=>{
  for(const [value,system]of [[1,'triclinic'],[2,'triclinic'],[3,'monoclinic'],[15,'monoclinic'],[16,'orthorhombic'],[74,'orthorhombic'],[75,'tetragonal'],[142,'tetragonal'],[143,'trigonal'],[167,'trigonal'],[168,'hexagonal'],[194,'hexagonal'],[195,'cubic'],[230,'cubic']])assert.equal(crystalSystem(value),system);
  for(const value of [0,231,62.5,'',NaN,Infinity])assert.equal(crystalSystem(value),null);
});
test('input template creates two typed requests',()=>{const rows=csvToRequests(inputTemplate());assert.equal(rows.length,2);assert.equal(rows[0].spacegroup_number_charge,62);assert.equal(rows[1].model_family,'svr');});
test('CSV parser supports BOM CRLF quotes commas and multiline cells',()=>{assert.deepEqual(parseCSV('\uFEFFa,b\r\n"one,two","line\nnext"\r\n"a""b",x\r\n'),[['a','b'],['one,two','line\nnext'],['a"b','x']]);});
test('CSV parser rejects malformed quoted fields',()=>{for(const input of ['a,b\n"x,y','a,b\nx"y,z','a,b\n"x"junk,y'])assert.throws(()=>parseCSV(input));});
test('CSV rejects label/provenance columns and duplicate headers',()=>{assert.throws(()=>csvToRequests(inputTemplate().replace('working_ion,','average_voltage_V,')),/Missing/);assert.throws(()=>csvToRequests(inputTemplate().replace('model_family','working_ion')),/unique/);assert.throws(()=>csvToRequests(inputTemplate().replace('model_family','target_voltage')),/Unexpected/);});
test('CSV rejects wrong widths, invalid SG, symmetry, and excess rows',()=>{const text=inputTemplate();assert.throws(()=>csvToRequests(text+'Li,FePO4\n'),/column count/);assert.throws(()=>csvToRequests(text.replaceAll(',62,',',62.5,')),/integer/);assert.throws(()=>csvToRequests(text.replaceAll('orthorhombic','cubic')),/does not match/);const rows=text.trim().split('\r\n');assert.throws(()=>csvToRequests([rows[0],...Array(129).fill(rows[1])].join('\n')),/128/);});
test('exports retain full voltage precision and model metadata',()=>{const p=prediction(),rows=parseCSV(predictionCSV([p])),header=rows[0];assert.equal(Number(rows[1][header.indexOf('predicted_voltage_V')]),p.predicted_voltage_V);assert.equal(rows[1][header.indexOf('candidate_id')],'dnn_scaled_0');assert.equal(rows[1][header.indexOf('warnings')],'Test fixture only');});
test('CSV escapes text while preserving negative numeric values',()=>{const csv=encodeCSV([['a,b','x"y','line\nnext',-1.25,'=1+1']]);assert.deepEqual(parseCSV(csv),[['a,b','x"y','line\nnext','-1.25',"'=1+1"]]);});
test('API result validation rejects missing or nonfinite values',()=>{assert.throws(()=>validatePredictions({...prediction(),predicted_voltage_V:NaN},1));assert.throws(()=>validatePredictions([prediction()],2));assert.throws(()=>validatePredictions({...prediction(),interval:{}},1));});
test('profile chart uses interval boundaries and keeps negative voltages',()=>{const g=profileGeometry([prediction(0,1,-1),prediction(1,3,2)]);assert.equal(g.segments[0].x2,g.segments[1].x1);assert.equal(g.segments[1].x2,g.W-g.right);assert.ok(g.segments[0].y>g.segments[1].y);});
test('flat profiles have a finite plotting range and gaps are rejected',()=>{const g=profileGeometry([prediction(0,1,3),prediction(1,2,3)]);assert.ok(g.segments.every(s=>Number.isFinite(s.y)));assert.equal(g.segments[0].y,g.segments[1].y);assert.throws(()=>profileGeometry([prediction(0,1),prediction(2,3)]),/contiguous/);});
test('server validation errors identify the relevant input row',()=>{assert.match(friendlyError([{loc:['body','items',2,'formula_charge'],msg:'Value error, Invalid host'}]),/Row 3: formula charge: Invalid host/);});
